"""每周精选生成器。

每周五跑，产出：
  - Supabase weekly_picks 表（后端查询用）
  - frontend/weekly/{YYYY-Www}.html 静态页（分享链接用）

选取规则（每域 top 8）:
  1. 过去 7 天新增或引用增长最快的论文
  2. fallback: 过去 30 天引用数最高的论文
"""

from __future__ import annotations
import os
from datetime import date, timedelta
from pathlib import Path

from backend.config import DOMAINS
from backend.db import get_client
from backend.pipeline.trending import compute_weekly_trending

PER_DOMAIN = 8
OUT_DIR = Path(__file__).resolve().parents[2] / "frontend" / "weekly"


def pick_for_domain(domain: str) -> list[dict]:
    picks = compute_weekly_trending(domain=domain, limit=PER_DOMAIN)
    if len(picks) >= PER_DOMAIN:
        return picks[:PER_DOMAIN]
    # fallback: 引用最高
    client = get_client()
    cutoff = (date.today() - timedelta(days=30)).isoformat()
    resp = (
        client.table("papers")
        .select("*")
        .contains("domains", [domain])
        .gte("published_at", cutoff)
        .order("citation_count", desc=True)
        .limit(PER_DOMAIN)
        .execute()
    )
    return resp.data


def render_html(week_label: str, picks_by_domain: dict[str, list[dict]]) -> str:
    sections = []
    for domain, papers in picks_by_domain.items():
        cfg = DOMAINS[domain]
        items = "\n".join(
            f"""<li><a href="{p.get('arxiv_url') or p.get('open_access_pdf') or '#'}" target="_blank">
                  <strong>{_esc(p['title'])}</strong></a>
                  <div class="meta">{p.get('venue') or ''} · {p.get('year') or ''} · 📊 {p.get('citation_count', 0)}</div>
                </li>"""
            for p in papers
        )
        sections.append(
            f"""<section><h2>{cfg['icon']} {cfg['label_zh']} / {cfg['label_en']}</h2>
            <ol>{items}</ol></section>"""
        )

    return f"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<title>Paperscope · Weekly {week_label}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body{{font-family:-apple-system,system-ui,sans-serif;max-width:780px;margin:40px auto;padding:0 20px;color:#222;line-height:1.6}}
  h1{{font-size:28px}} h2{{margin-top:2em;border-bottom:2px solid #eee;padding-bottom:.3em}}
  ol{{padding-left:1.2em}} li{{margin:.8em 0}} .meta{{color:#888;font-size:.85em}}
  a{{color:#2563eb;text-decoration:none}} a:hover{{text-decoration:underline}}
</style></head>
<body>
  <h1>🔭 Paperscope Weekly · {week_label}</h1>
  <p>本期精选三领域共 {sum(len(v) for v in picks_by_domain.values())} 篇论文。</p>
  {''.join(sections)}
  <footer style="margin-top:3em;color:#999;font-size:.8em">
    Generated by Paperscope · <a href="/">返回主站</a>
  </footer>
</body></html>"""


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    today = date.today()
    week_start = today - timedelta(days=today.weekday())  # 本周一
    week_label = f"{week_start.isocalendar().year}-W{week_start.isocalendar().week:02d}"

    picks_by_domain: dict[str, list[dict]] = {}
    client = get_client()
    for domain in DOMAINS:
        picks = pick_for_domain(domain)
        picks_by_domain[domain] = picks
        if picks:
            client.table("weekly_picks").upsert({
                "week_start": week_start.isoformat(),
                "domain": domain,
                "paper_ids": [p["id"] for p in picks],
            }, on_conflict="week_start,domain").execute()

    html = render_html(week_label, picks_by_domain)
    out = OUT_DIR / f"{week_label}.html"
    out.write_text(html, encoding="utf-8")
    # 更新 index.html 作为最新一期
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")
    print(f"[weekly] wrote {out}")


if __name__ == "__main__":
    main()
